[package]
name = "iptv_desktop"
version = "0.1.0"
edition = "2024"

[dependencies]
directories = "6.0.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
libcore = {package = "core", git = "https://github.com/ebaah46/iptv-core.git"}
libcore_api = {package = "iptv-adapter-api", git = "https://github.com/ebaah46/iptv-core.git"}
libcore_cache = {package = "iptv-adapter-cache", git = "https://github.com/ebaah46/iptv-core.git"}
anyhow = "1.0.104"
iced = "0.14.0"
tokio = { version = "1", features = ["rt"] }
iced_aw = { version = "0.14.1", features = ["full"], default-features = false }

