import { HomeScreen } from "screens/home_screen.slint";
import { HomeState } from "globals/home_state.slint";
import { PlayerScreen } from "screens/player_screen.slint";
import { NavigationState, Page } from "globals/navigation_state.slint";

export { HomeState, NavigationState, Page }
export component MainWindow inherits Window {
    width: 1024px;
    height: 720px;
    title: "IPTV Desktop";

    background: #13131a;

    HomeScreen {
        width: 100%;
        height: 100%;
        visible: NavigationState.current_page == Page.Home;
    }

    PlayerScreen {
        width: 100%;
        height: 100%;
        visible: NavigationState.current_page == Page.Player;
    }

    // Navigation is handled in the Rust controller layer
}
